In [40]:
import requests # pip install requests
from bs4 import BeautifulSoup as bs # pip install beautifulsoup4

In [41]:
r = requests.get("https://www.timesjobs.com/candidate/job-search.html?searchType=personalizedSearch&from=submit&txtKeywords=data+analyst&txtLocation=")

# Convert to a beautiful soup object
soup = bs(r.content, 'lxml')

# Print out our html
#print(soup.prettify())

In [42]:
# we first  did job = soup.find then carried on with soup.find_all & jobs 
# li clearfix job-bx wht-shd-bx
jobs = soup.find_all('li' , class_ = 'clearfix job-bx wht-shd-bx')
#print(job)
for job in jobs :

  #joblist-comp-name h3
  company_name = job.find('h3',class_ = 'joblist-comp-name').text.strip()
  #print(company_name.text.strip())


  # span srp-skills
  skills = job.find('span' , class_ = 'srp-skills').text.strip()
  #print(skills.text.strip())


  # span sim-posted
  job_posted = job.find('span' , class_ = 'sim-posted').text.strip()

  #to access more info 
  more_info = job.find('h2').a['href']
  #print(more_info)



  print(f''' 
  Company name : {company_name}
  Skills : {skills}
  Posted : {job_posted}
  For more information : {more_info}
  ''')
  print("*"*200)

  Company name : infoanalytica consulting pvt ltd
  Skills : business rules  ,  sql  ,  Data Analyst
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-infoanalytica-consulting-pvt-ltd-ahmedabad-5-to-8-yrs-jobid-xEPbiv5__PLUS__2aRzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : Schneider Electric Pvt Ltd
  Skills : data visualization  ,  crm  ,  data analyst  ,  alteryx  ,  tableau
  Posted : Posted 6 days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-schneider-electric-pvt-ltd-philippines-2-to-5-yrs-jobid-q46BKjcDM9JzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : ikomet Technology Solutions Pvt. Ltd.
  Skills : macros  ,  visualization  ,  bi  ,  data analyst  ,  vba
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-ikomet-technology-solutions-pvt-ltd-chennai-0-to-3-yrs-jobid-uYgM1Mifhr1zpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : ACENET TECHNOLOGIES
  Skills : bi  ,  dashboards  ,  data analyst  ,  sql  ,  tableau
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-acenet-technologies-gurgaon-delhi-delhi-ncr-pune-bengaluru-bangalore-10-to-15-yrs-jobid-vlpD6MnRaX9zpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : Koch Global Business Services
  Skills : functional analyst  ,  dashboards  ,  data analytics  ,  data analysis  ,  data analyst  ,  tableau
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-koch-global-business-services-bengaluru-bangalore-0-to-3-yrs-jobid-ZpBIzDjDvqRzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : Zealogics LLC.
  Skills : data analysis  ,  gap analysis  ,  data analyst  ,  security  ,  trading systems
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-zealogics-llc-0-to-3-yrs-jobid-bbZfTOHQeHZzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : ADROIT LEARNING AND MANPOWER PVT LTD
  Skills : data analysis  ,  dashboards  ,  data analyst  ,  sql  ,  tableau  ,  infrastructure  ,  data visualization
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-adroit-learning-and-manpower-pvt-ltd-ahmedabad-7-to-10-yrs-jobid-O6rsbebTEJNzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : Schneider Electric Pvt Ltd
  Skills : business requirements  ,  sql  ,  data visualization  ,  crm  ,  functional specifications  ,  oracle  ,  ms access  ,  data analyst  ,  alteryx  ,  tableau  ,  infrastructure
  Posted : Posted 1 day ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-schneider-electric-pvt-ltd-bengaluru-bangalore-1-to-4-yrs-jobid-toFNuf9xULVzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : Schneider Electric Pvt Ltd
  Skills : business requirements  ,  sql  ,  data visualization  ,  crm  ,  functional specifications  ,  oracle  ,  ms access  ,  data analyst  ,  alteryx  ,  tableau  ,  infrastructure
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-schneider-electric-pvt-ltd-bengaluru-bangalore-1-to-4-yrs-jobid-ZAN3UmlpKf1zpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : crescendo global
  Skills : bi  ,  sql  ,  data science  ,  press  ,  data analytics  ,  data analysis  ,  consulting  ,  data analyst  ,  tableau  ,  written communication
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-crescendo-global-gurgaon-mumbai-pune-3-to-7-yrs-jobid-MzLw6J8m1HxzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : Rapido
  Skills : data analysis  ,  dashboards  ,  data analyst  ,  sql  ,  tableau  ,  data cleaning  ,  data scientist  ,  data visualization
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-rapido-bengaluru-bangalore-2-to-4-yrs-jobid-fbBwu4Y9u6tzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : Target Corporation India Pvt Ltd
  Skills : dashboards  ,  sql  ,  data analysis  ,  data analytics  ,  data reports  ,  data analyst  ,  business intelligence reporting  ,  statistical analysis
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-target-corporation-india-pvt-ltd-bengaluru-bangalore-2-to-5-yrs-jobid-uSOuN5Y4J__SLASH__ZzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : Jio Saavan
  Skills : data mining  ,  dashboards  ,  sql  ,  advanced analytics  ,  data analysis  ,  mobile  ,  data analyst  ,  analytics reporting  ,  tableau
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-jio-saavan-gurgaon-mumbai-bengaluru-bangalore-3-to-4-yrs-jobid-lr1HqOpdOEtzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : Veeva Systems
  Skills : bi  ,  sql  ,  crm  ,  san  ,  data analysis  ,  customer success  ,  information management  ,  data analyst  ,  tableau
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-veeva-systems-china-0-to-3-yrs-jobid-gziX9I2uKb5zpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : freshdesk
  Skills : business requirements  ,  bi  ,  sql  ,  data visualization  ,  crm  ,  san  ,  customer success  ,  gap analysis  ,  business environment  ,  data analyst  ,  tableau
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-freshdesk-chennai-2-to-3-yrs-jobid-xFmH37LyYldzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : ANR SOFTWARE PVT LTD
  Skills : data analytics  ,  information management  ,  sas  ,  spss  ,  data analyst  ,  sql  ,  data science  ,  written communication
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-anr-software-pvt-ltd-noida-greater-noida-0-to-1-yrs-jobid-wiKqbbFOouJzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : legalwiz.in private limited
  Skills : information technology  ,  data mining  ,  data warehousing  ,  storage  ,  dashboards  ,  data analyst  ,  tableau  ,  data visualization
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-legalwiz-in-private-limited-ahmedabad-0-to-1-yrs-jobid-Yg11HKMOaORzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : Nanobi data and analytics pvt ltd
  Skills : sas  ,  consulting  ,  bi  ,  spss  ,  data analyst  ,  sql  ,  data science  ,  data scientist
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-nanobi-data-and-analytics-pvt-ltd-bengaluru-bangalore-7-to-9-yrs-jobid-Uep6ZgmCjuxzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : druva software
  Skills : bi  ,  software management  ,  dashboards  ,  sql  ,  data analysis  ,  customer success  ,  business analysis  ,  business analytics  ,  data analyst  ,  alteryx  ,  tableau
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-druva-software-pune-3-to-6-yrs-jobid-qnD6aNfhumlzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : Optimas Solutions
  Skills : business requirements  ,  data mining  ,  bi  ,  sql  ,  data visualization  ,  data analysis  ,  director  ,  business analytics  ,  data analyst  ,  tableau  ,  infrastructure
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-optimas-solutions-0-to-3-yrs-jobid-Xa2OFXwLAC1zpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : RGF Professional
  Skills : visualization  ,  dashboards  ,  data analytics  ,  mining  ,  data mining  ,  bi  ,  data scientist  ,  data analysis  ,  consulting  ,  data analyst  ,  tableau  ,  analyst
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-rgf-professional-hyderabad-secunderabad-4-to-8-yrs-jobid-lZ7dTnij5wlzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : TE Connectivity Ltd
  Skills : information technology  ,  bi  ,  dashboards  ,  sql  ,  database  ,  solution design  ,  crm  ,  macros  ,  data analysis  ,  data analytics  ,  sas  ,  mining  ,  data analyst  ,  alteryx  ,  tableau  ,  business objects
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-te-connectivity-ltd-bengaluru-bangalore-2-to-5-yrs-jobid-QFdA2diT4x5zpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : Koch Global Business Services
  Skills : business requirements  ,  information technology  ,  dashboards  ,  advanced analytics  ,  data cleaning  ,  bi  ,  business solutions  ,  sql  ,  data science  ,  solution design  ,  data analysis  ,  sas  ,  spotfire  ,  consulting  ,  data analyst  ,  tableau  ,  consultant  ,  analyst
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-koch-global-business-services-bengaluru-bangalore-4-to-7-yrs-jobid-HmqxyEZAmVxzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : ion trading india pvt. ltd.
  Skills : bi  ,  dashboards  ,  sql  ,  trading systems  ,  software engineering  ,  data visualization  ,  predictive analysis  ,  electronic trading  ,  data analysis  ,  consulting  ,  data analyst  ,  written communication  ,  infrastructure
  Posted : Posted few days ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-ion-trading-india-pvt-ltd-noida-greater-noida-0-to-3-yrs-jobid-QDeB2K4ih45zpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

  Company name : Nielsen Research Ltd. Co.
  Skills : market research  ,  marketing communication  ,  media planning
  Posted : Posted 1 day ago
  For more information : https://www.timesjobs.com/job-detail/data-analyst-nielsen-research-ltd-co-0-to-3-yrs-jobid-xT72SmQgByZzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

Creating a web scrapper for jobs posted only a few days ago :

In [43]:
for job in jobs :
  # span sim-posted
  job_posted = job.find('span' , class_ = 'sim-posted').text.strip()
  if 'few' in job_posted :

    #joblist-comp-name h3
    company_name = job.find('h3',class_ = 'joblist-comp-name').text.strip()
    #print(company_name.text.strip())


    # span srp-skills
    skills = job.find('span' , class_ = 'srp-skills').text.strip()
    #print(skills.text.strip())

    #to access more info 
    more_info = job.find('h2').a['href']
    #print(more_info)



    print(f''' 
    Company name : {company_name}
    Skills : {skills}
    Posted : {job_posted}
    For more information : {more_info}
    ''')
    print("*"*200)

    Company name : infoanalytica consulting pvt ltd
    Skills : business rules  ,  sql  ,  Data Analyst
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-infoanalytica-consulting-pvt-ltd-ahmedabad-5-to-8-yrs-jobid-xEPbiv5__PLUS__2aRzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : ikomet Technology Solutions Pvt. Ltd.
    Skills : macros  ,  visualization  ,  bi  ,  data analyst  ,  vba
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-ikomet-technology-solutions-pvt-ltd-chennai-0-to-3-yrs-jobid-uYgM1Mifhr1zpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : ACENET TECHNOLOGIES
    Skills : bi  ,  dashboards  ,  data analyst  ,  sql  ,  tableau
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-acenet-technologies-gurgaon-delhi-delhi-ncr-pune-bengaluru-bangalore-10-to-15-yrs-jobid-vlpD6MnRaX9zpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : Koch Global Business Services
    Skills : functional analyst  ,  dashboards  ,  data analytics  ,  data analysis  ,  data analyst  ,  tableau
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-koch-global-business-services-bengaluru-bangalore-0-to-3-yrs-jobid-ZpBIzDjDvqRzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : Zealogics LLC.
    Skills : data analysis  ,  gap analysis  ,  data analyst  ,  security  ,  trading systems
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-zealogics-llc-0-to-3-yrs-jobid-bbZfTOHQeHZzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : ADROIT LEARNING AND MANPOWER PVT LTD
    Skills : data analysis  ,  dashboards  ,  data analyst  ,  sql  ,  tableau  ,  infrastructure  ,  data visualization
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-adroit-learning-and-manpower-pvt-ltd-ahmedabad-7-to-10-yrs-jobid-O6rsbebTEJNzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : Schneider Electric Pvt Ltd
    Skills : business requirements  ,  sql  ,  data visualization  ,  crm  ,  functional specifications  ,  oracle  ,  ms access  ,  data analyst  ,  alteryx  ,  tableau  ,  infrastructure
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-schneider-electric-pvt-ltd-bengaluru-bangalore-1-to-4-yrs-jobid-ZAN3UmlpKf1zpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : crescendo global
    Skills : bi  ,  sql  ,  data science  ,  press  ,  data analytics  ,  data analysis  ,  consulting  ,  data analyst  ,  tableau  ,  written communication
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-crescendo-global-gurgaon-mumbai-pune-3-to-7-yrs-jobid-MzLw6J8m1HxzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : Rapido
    Skills : data analysis  ,  dashboards  ,  data analyst  ,  sql  ,  tableau  ,  data cleaning  ,  data scientist  ,  data visualization
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-rapido-bengaluru-bangalore-2-to-4-yrs-jobid-fbBwu4Y9u6tzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : Target Corporation India Pvt Ltd
    Skills : dashboards  ,  sql  ,  data analysis  ,  data analytics  ,  data reports  ,  data analyst  ,  business intelligence reporting  ,  statistical analysis
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-target-corporation-india-pvt-ltd-bengaluru-bangalore-2-to-5-yrs-jobid-uSOuN5Y4J__SLASH__ZzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : Jio Saavan
    Skills : data mining  ,  dashboards  ,  sql  ,  advanced analytics  ,  data analysis  ,  mobile  ,  data analyst  ,  analytics reporting  ,  tableau
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-jio-saavan-gurgaon-mumbai-bengaluru-bangalore-3-to-4-yrs-jobid-lr1HqOpdOEtzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : Veeva Systems
    Skills : bi  ,  sql  ,  crm  ,  san  ,  data analysis  ,  customer success  ,  information management  ,  data analyst  ,  tableau
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-veeva-systems-china-0-to-3-yrs-jobid-gziX9I2uKb5zpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : freshdesk
    Skills : business requirements  ,  bi  ,  sql  ,  data visualization  ,  crm  ,  san  ,  customer success  ,  gap analysis  ,  business environment  ,  data analyst  ,  tableau
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-freshdesk-chennai-2-to-3-yrs-jobid-xFmH37LyYldzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : ANR SOFTWARE PVT LTD
    Skills : data analytics  ,  information management  ,  sas  ,  spss  ,  data analyst  ,  sql  ,  data science  ,  written communication
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-anr-software-pvt-ltd-noida-greater-noida-0-to-1-yrs-jobid-wiKqbbFOouJzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : legalwiz.in private limited
    Skills : information technology  ,  data mining  ,  data warehousing  ,  storage  ,  dashboards  ,  data analyst  ,  tableau  ,  data visualization
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-legalwiz-in-private-limited-ahmedabad-0-to-1-yrs-jobid-Yg11HKMOaORzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : Nanobi data and analytics pvt ltd
    Skills : sas  ,  consulting  ,  bi  ,  spss  ,  data analyst  ,  sql  ,  data science  ,  data scientist
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-nanobi-data-and-analytics-pvt-ltd-bengaluru-bangalore-7-to-9-yrs-jobid-Uep6ZgmCjuxzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : druva software
    Skills : bi  ,  software management  ,  dashboards  ,  sql  ,  data analysis  ,  customer success  ,  business analysis  ,  business analytics  ,  data analyst  ,  alteryx  ,  tableau
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-druva-software-pune-3-to-6-yrs-jobid-qnD6aNfhumlzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : Optimas Solutions
    Skills : business requirements  ,  data mining  ,  bi  ,  sql  ,  data visualization  ,  data analysis  ,  director  ,  business analytics  ,  data analyst  ,  tableau  ,  infrastructure
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-optimas-solutions-0-to-3-yrs-jobid-Xa2OFXwLAC1zpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : RGF Professional
    Skills : visualization  ,  dashboards  ,  data analytics  ,  mining  ,  data mining  ,  bi  ,  data scientist  ,  data analysis  ,  consulting  ,  data analyst  ,  tableau  ,  analyst
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-rgf-professional-hyderabad-secunderabad-4-to-8-yrs-jobid-lZ7dTnij5wlzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : TE Connectivity Ltd
    Skills : information technology  ,  bi  ,  dashboards  ,  sql  ,  database  ,  solution design  ,  crm  ,  macros  ,  data analysis  ,  data analytics  ,  sas  ,  mining  ,  data analyst  ,  alteryx  ,  tableau  ,  business objects
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-te-connectivity-ltd-bengaluru-bangalore-2-to-5-yrs-jobid-QFdA2diT4x5zpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : Koch Global Business Services
    Skills : business requirements  ,  information technology  ,  dashboards  ,  advanced analytics  ,  data cleaning  ,  bi  ,  business solutions  ,  sql  ,  data science  ,  solution design  ,  data analysis  ,  sas  ,  spotfire  ,  consulting  ,  data analyst  ,  tableau  ,  consultant  ,  analyst
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-koch-global-business-services-bengaluru-bangalore-4-to-7-yrs-jobid-HmqxyEZAmVxzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

    Company name : ion trading india pvt. ltd.
    Skills : bi  ,  dashboards  ,  sql  ,  trading systems  ,  software engineering  ,  data visualization  ,  predictive analysis  ,  electronic trading  ,  data analysis  ,  consulting  ,  data analyst  ,  written communication  ,  infrastructure
    Posted : Posted few days ago
    For more information : https://www.timesjobs.com/job-detail/data-analyst-ion-trading-india-pvt-ltd-noida-greater-noida-0-to-3-yrs-jobid-QDeB2K4ih45zpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

Creating a web scrapper for jobs posted only a few days ago & also filtering out jobs with skill the user isn't familiar with :

In [44]:
print("Please enter the skill you are unfamiliar with")
unfamiliar_skill = input('>')

for job in jobs :
  # span sim-posted
  job_posted = job.find('span' , class_ = 'sim-posted').text.strip()
  if 'few' in job_posted :

    #joblist-comp-name h3
    company_name = job.find('h3',class_ = 'joblist-comp-name').text.strip()
    #print(company_name.text.strip())


    # span srp-skills
    skills = job.find('span' , class_ = 'srp-skills').text.strip()
    #print(skills.text.strip())

    #to access more info 
    more_info = job.find('h2').a['href']
    #print(more_info)

    if unfamiliar_skills not in skills:

      print(f''' 
      Company name : {company_name}
      Skills : {skills}
      Posted : {job_posted}
      For more information : {more_info}
      ''')
      print("*"*200)

Please enter the skill you are unfamiliar with
>sql

      Company name : ikomet Technology Solutions Pvt. Ltd.
      Skills : macros  ,  visualization  ,  bi  ,  data analyst  ,  vba
      Posted : Posted few days ago
      For more information : https://www.timesjobs.com/job-detail/data-analyst-ikomet-technology-solutions-pvt-ltd-chennai-0-to-3-yrs-jobid-uYgM1Mifhr1zpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

      Company name : Koch Global Business Services
      Skills : functional analyst  ,  dashboards  ,  data analytics  ,  data analysis  ,  data analyst  ,  tableau
      Posted : Posted few days ago
      For more information : https://www.timesjobs.com/job-detail/data-analyst-koch-global-business-services-bengaluru-bangalore-0-to-3-yrs-jobid-ZpBIzDjDvqRzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

      Company name : Zealogics LLC.
      Skills : data analysis  ,  gap analysis  ,  data analyst  ,  security  ,  trading systems
      Posted : Posted few days ago
      For more information : https://www.timesjobs.com/job-detail/data-analyst-zealogics-llc-0-to-3-yrs-jobid-bbZfTOHQeHZzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

      Company name : legalwiz.in private limited
      Skills : information technology  ,  data mining  ,  data warehousing  ,  storage  ,  dashboards  ,  data analyst  ,  tableau  ,  data visualization
      Posted : Posted few days ago
      For more information : https://www.timesjobs.com/job-detail/data-analyst-legalwiz-in-private-limited-ahmedabad-0-to-1-yrs-jobid-Yg11HKMOaORzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************

      Company name : RGF Professional
      Skills : visualization  ,  dashboards  ,  data analytics  ,  mining  ,  data mining  ,  bi  ,  data scientist  ,  data analysis  ,  consulting  ,  data analyst  ,  tableau  ,  analyst
      Posted : Posted few days ago
      For more information : https://www.timesjobs.com/job-detail/data-analyst-rgf-professional-hyderabad-secunderabad-4-to-8-yrs-jobid-lZ7dTnij5wlzpSvf__PLUS__uAgZw==&source=srp

********************************************************************************************************************************************************************************************************